# -*- coding: utf-8 -*-
"""MAIN BOOT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bttwH5Ma2xHMLSeggLLxAMrG1uQAQ1w-
"""

#Write a program for prime number. Dont include 1 as prime number
x=int(input("Enter the Number:"))
flag=0
if(x==2):
  print("2 is a prime number")
else:
  for i in range(2,x):
    r=x%i
    if(r==0):
      flag=1
      break
    else:
      flag=0
if(flag==1):
  print("Number is not prime")
else:
  print("Number is prime")

#Write a program using def function with one Arugument
def func(fname):
  print("My name is",fname)
func("Shriram")

#Write a program using def function with 2 Arugments
def func(fname,lname):
  print("My name is",fname,lname)
func("Shriram","Vaidyanathan")

#Write a program getting age as input using def function
def func(Age):
  print("My age is",Age)
x=int(input("Enter your age "))
func(x)

#Write a program for list of aruguments using def func() example
def func(*x):
  print("The students in the class",x)
func("Sukanya","Shriram","RRRR","TTTT")

#Write a program using def func() for add,sub,div,multiply taking input of two valued from user
def ADD(x,y):
  SUM=x+y
  print("SUM=",SUM)
def SUB(x,y):
  sub=x-y
  print("sub=",sub)
def DIV(x,y):
  div=x/y
  print("div=",div)
def MUL(x,y):
  mul=x*y
  print("mul=",mul)

x,y=list(map(int,input().split()))
O=input("Select the Arithemetic Opertion: +,-,/,* ")
if O=='+':
  ADD(x,y)
elif O=="-":
  SUB(x,y)
elif O=="/":
  DIV(x,y)
elif O=="*":
  MUL(x,y)
else:
  print("Invalid operator selected")

#Write a program for to check input from user is palindrome
A=input()
B=A[::-1]
if A==B:
  print("PALINDROM",B)
else:
  print("Not a PALINDROM")

#Write a program for PALINDROME using func as argument
def PALIN1(s):
  s=s[::-1]
  return s
def func2(PALIN):
  A=input("Enter the string: ")
  B=PALIN(A)
  if A==B:
    print("PALINDROME")
  else:
    print("NOT A PALINDROME")
func2(PALIN1)

#Write a program using func to call two func's as argument
def f2():
  print("Hello")

def f3():
  print("World")

def f1(w):     #variable of f1 should always be the same while calling(example w)
  w()

f1(f2)
f1(f3)

#LIST COMPREHENSION with FOR
fruits=["apple","Banna","Cheery","Mango"]
newlist=[x for x in fruits]
print(newlist)

#LIST COMPREHENSION VIA FOR LOOP
fruits=["apple","Banna","Cheery","Mango"]
newlist=[]
for x in fruits:
  if 'a' in x:
    newlist.append(x)
print(newlist)

#LIST COMPREHENSION SHORT FORM TO THE ABOVE PROGRAM 
fruits=["apple","Banna","Cheery","Mango"]
newlist=[x for x in fruits if 'a' in x]
print(newlist)

#LIST COMPREHENSION for REPLACE OF LIST TO ANOTHER INDEX VARIABLE
fruits=["apple","Banana","Cheery","Mango"]
newlist=[x if x!="Banana" else "orange" for x in fruits]
print(newlist)

#USING LIST COMPREHENSION PRINT RANGE OF RUMBERS LESSER THAN 5
newlist=[x for x in range(10) if x<5]
print(newlist)

#USING LIST COMPREHENSION CHANGE THE VARIABLE INTO NEWLIST VARIABLE Ex:"Hello"
fruits=["apple","banana","cherry","Kiwi","Mango"]
newlist=['hello' for x in fruits]
print(newlist)

#FILE HANDLING
file=open("newfile.txt","r") #"r"--> read mode "newfile.txt"-->file name
for each in file: 
  print(each)

#FILE HANDLING READ MODE
file=open("filename.txt","r")
if(file):
  print("open")
else:
  print("close")
for each in file:
  print=(each)

#FILE HANDLING READ MODE INDEX PRINT
file=open("newfile.txt","r")
print(file.read())   #Gives whole file name
print(file.read(5))  #Gives name of the file name with specific index

#FILE READING "r+"
f=open("newfile4.txt","r+")  #for"r+" you should read and write. if you write and print(f.read()) it wont be created
print(f.read())              #for "r+" you should have an exisiting file in the folder
f.write("Hello, this is the new file") #"r+" used for reading and writing
f.close()

#FILE READING "w+"
f=open("newfile4.txt","w+") #for "w+" Creates a file in the folder
f.write("Hello") #for "w+" it is used for writing and reading
print(f.read())
f.close()

#FILE HANDLING To write in a file
file=open("newfile1.txt","w") #"w" write mode isused for making a new file
file.write("This is the 2nd Session") #Writed the content in the file
file.write("We are doing file handling in python") #Wrie mode will replace the entire content of the file
file.close()

#FILE HANDLING To Append
file=open("newfile1.txt","a") #Append to the end of the content of the file
file.write("Appending to the file")
file close()

#FILE HANDLING f.seek(0)