# -*- coding: utf-8 -*-
"""Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14pTS2oLdw_9OHs8R8EmlSP-lCZajaJ4h
"""

print('Hello World')

#list
L=[50,3.14,'Guvi',True,[1,2,3,4,5]] #list can contain any dat type or data structure
#   0  1     2     3      4         #List can be changed,manipulated
print(L[2])

print(L[4])

print(L[4][3])

print(L[-1][-3])

S=[1,2,3,88,77]
print(S[-2])

#Tuple
T=(50,3.14,'Guvi',True,[1,2,3,4,5])    #Tuple can contain any data type

dir(list)

dir(tuple)

L=[1,2,3,4,5,6,(55,23,44)]
print(L)
T=tuple(L)
tuple(T)

"""function() List[] tuple=() set{} Dict={}"""

#set
S={1,2,5,55,9,86,23,24}
print(S)

"""Sets are used to store multiple items in a single variable."""

#Dict
D={'Name':'Sachin',
   'Age':35,
   'Salary':30000}
print(D['Name'])

print(D)

print('Name: ',D['Name'])
print('Age: ',D['Age'])
print('Salary ',D['Salary'])

#write a program to determine the character entered by the user
char=input("Press any key: ")
if(char.isalpha()):
  print("The user has entered a character")
if(char.isdigit()):
  print("The user has entered a digit")
if(char.isspace()):
  print("The user entered a white space character")

#write a program to detrmine whether a person is eligible to vote or not. if he is not eligible, display how many years are left to be eligible
age=int(input("Enter your age: "))
if age>18:
  print("You are eligible to vote")
else:
  yrs=18-age
  print("You have to wait "+str(yrs)+" years to cast yout vote")

#write a program to find larger of two number 
a=int(input("enter the value of a: "))
b=int(input("enter the value of b: "))
if a>b:
  print("Larger number is ",a)
else:
  print("Larger number is ",b)

#write a program to find whether the given number is even or odd
num=int(input())
if num%2==0:
  print(num,"is even")
else:
  print(num,"is odd")

#write a program to enter any character.if the entered character is in lowercase then convert it into uppercase and if it is an uppercase the converet it into lowercase
ch=input()
if ch>='A' and ch<="Z":
  ch=ch.lower()
  print("The entered character was in uppercase. In lowercase it is: ",ch)
else:
  ch=ch.upper()
  print("The entered character was in lowercase. In uppercase it is: ",ch)

#A company decides to give bonus to all its employees on diwali. A 5% bonus on salary is given to the male workers and 10% bonus on salary to the female workers
#Write a program to enter the salary of the employee and sex of the employee.
Sex=input("Enter the sex (m,f): ")
sal=int(input("Enter the salary of the employee: "))
if (Sex=='m'):
  bonus=0.05*sal
else:
  bonus=0.10*sal
amt_to_paid=sal+bonus
print("Salary: ",sal)
print("Bonus: ",bonus)
print("Amount to be paid: ",amt_to_paid)

#Program to demonstrate operation on lists
list=['a','bc',78,1.23]
list2=['d',78]
print(list)
print("Print first element of the list",list[0])
print("Print elements starting from 2nd till 3rd",list[1:3])
print("print elements staring from 3rd element",list[2:])
print("Repeat list",list*2)
print("Concatenates two lists",(list+list2))

#program to read variables from the user
name=input("What's your name? ")
age=int(input())
print("My name is "+str(name)+",I am "+str(age)+" years old")

#program to demonstrate operations on tuple
Tup=('a','bc',78,1.23)
Tup2=('d',78)
print(Tup)
print("Print first element of tuple",Tup[0])
print("Print elements starting from 2nd till 3rd",Tup[1:3])
print("Print elements starting from 3rd element",Tup[2:])
print("Repeat Tuple",Tup*2)
print("Concatenates two tuple",(Tup+Tup2))

#program that perform addition and multiplication on string variables
S=input()
print(S+' 4')
print(S*2)

#program performing slice operation on strings
A="Python is Easy !!!"
print(A)
print(A[0])
print(A[3:9])
print(A[4:])
print(A[-1])
print(A[:5])
print(A[::-1])

#Write a program to calculate area of triangle using heron's formula
a=float(input("Enter the first side of the triangle: "))
b=float(input("Enter the second side of the triangle: "))
c=float(input("Enter the third side of the triangle: "))
S=(a+b+c)/2
area=(S*(S-a)*(S-b)*(S-c))**(1/2)
print("Area= ","%.2f"%area)

#program that prompts the user to enter a number then print its interval 
num=int(input("Enter any number from 0-30:"))
if num>=0 and num<=10:
  print("It is in the range 0-10")
if num>=10 and num<=20:
  print("It is in the range 0-20")
if num>=20 and num<=30:
  print("It is in the range 0-30")

#program to test whether a number entered by the user is negative,positive or equal to zero
num=int(input("Enter any number: "))
if num==0:
  print("The Value is equal to zero")
elif num>0:
  print("The Value is Positive")
else:
  print("The Value is Negative")

#Write a program to determine whether the character entered is a vowel or not
ch=input("Enter the Character: ")
if ch=='A' or ch=='E' or ch=='I' or ch=='O' or ch=='U':
  print(ch,"is a vowel")
elif  ch=='a' or ch=='e' or ch=='i' or ch=='o' or ch=='u':
  print(ch,"is a vowel")
else:
  print(ch,"is not a vowel")

#Write a program to find the greates number from 3 numbers
num1=int(input("Enter the 1st Number: "))
num2=int(input("Enter the 2nd Number: "))
num3=int(input("Enter the 3rd Number: "))
if num1>num2 and num1>num3:
  print(num1,"is the greatest number")
elif num2>num1 and num2>num3:
  print(num2,"is the greatest number")
else:
  print(num3,"is the greatest number")

#Write a program that prompts the user to enter a number between 1-7 ad the displays the coresponding day of the week
num=int(input("Enter day number in a week: "))
if num==1:
  print("Sunday")
elif num==2:
  print("Monday")
elif num==3:
  print("Tuesday")
elif num==4:
  print("Wednesday")
elif num==5:
  print("Thursday")
elif num==6:
  print("Friday")
elif num==7:
  print("Saturday")
else:
  print("Wrong Input")

#Write a program to calcuate tax giventhe following conditions
#If income is less than 1,50,000 then no tax
#if taxable income is 1,50,001-300,000 then charge is 10% tax
#If taxable income is 3,00,001-500,000 then charge is 20% tax
#if taxable income is above 5,00,001 then charge is 30% tax
I=int(input("Enter the Income: "))
print("Income is ",I)
MIN1=150001
MAX1=300,000
TAX1=0.10
MIN2=300001
MAX2=500000
TAX2=0.20
MIN3=500001
if I<=150000:
  print("No tax")
elif I<=MIN1 and I>=MAX1:
  T=I*TAX1
  print(T,"is Tax Value")
elif I<=MIN2 and I>=MAX2:
  T=I*TAX2
  print(T,"is Tax Value")
else:
  I>=MIN3
  T=I*0.30
  print(T,"is Tax Value")

#Write a program to enter the marks of a student in four subjects.Then calculate the TOTAL and AGGREGATE and display the GRADE obtained by the student
#If students scores an aggregate greater than 75% the grade is distinction.If aggregate is 60>= and <75 then grade is First Division.
#If aggregate is 50>= and <=60 then the grade is Second Divison.If Aggregate is 40>= and <50, then the grade is third divison 
#else grade is fail 
M1=int(input("Enter the marks of Mathematics: "))
M2=int(input("Enter the marks of Science: "))
M3=int(input("Enter the marks of English: "))
M4=int(input("Entee the marks of Social: "))
T=M1+M2+M3+M4
Avg=float(T)/4
print("The Total Marks is: ",T," & The average is: ",Avg)
if Avg>75:
  print("Grade-Distinction")
elif Avg>=60 and Avg<75:
  print("Grade-First Division")
elif Avg>=50 and Avg<=60:
  print("Grade-Second Division")
elif Avg>=40 and Avg<50:
  print("Grade-Thrid Divison")
else:
  print("Grade-FAIL")

#Program to print first 10 number in while loop
i=0
while i<=10:
  print(i)
  i=i+1

#Write a program to calculate the sum and avergae of first 10 numbers
i=0
s=0
while i<=10:
  s=s+i
  i=i+1
print("Sum of first 10 numbers is: ",s)
avg=float(s)/10
print("Average of first 10 numbers is: ",avg)

#write a program to print 20 horizontal asterisks
i=0
while i<=20:
  print("*",end='')
  i=i+1